---
- hosts: website
  vars:
    ubuntu_release: lucid
  vars_files:
    - variables/project.yml
    - variables/users.yml
    - variables/rbenv.yml
    - variables/nginx.yml
  roles:
    - bootstrap
    - users
    - rbenv
    - fetcher
    - deployer
    - nginx
